=== Agalo3132/ProgramacionPrimero/lenguajemarcas/validacion_canciones.dtd
<!ELEMENT discoteca (album+)>
<!ELEMENT album ((artista|artistas), genero, canciones)>
<!ELEMENT genero ANY>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT subgenero (#PCDATA)>
<!ELEMENT canciones (cancion+)>
<!ELEMENT cancion (#PCDATA)>
<!ELEMENT artistas (artista+)>
<!ATTLIST cancion numero CDATA #REQUIRED>

=== Agalo3132/ProgramacionPrimero/lenguajemarcas/prururueva.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE discoteca SYSTEM "validacion_canciones.dtd">
<discoteca>
    <album>
        <artista>Platero &amp; yo</artista>
    <genero>
        rock
        <subgenero>sinfonico</subgenero>
    </genero>
        <canciones>
            <cancion numero="1">holalola</cancion>
            <cancion numero="2">adiosmadios</cancion>
            <cancion numero="1">heyrey</cancion>
        </canciones>       
    </album>
</discoteca>
